[workspace]
channels = ["conda-forge", "https://repo.prefix.dev/econforge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[tasks]
lab = "jupyter lab"
watch = "jlpm watch & jupyter lab"

[dependencies]
jupyterlab = ">=4.0.0,<5"
jupyterlab_dyno = { path = "." }
dyno = ">=0.1.5.dev7"
nodejs = ">=24.4.0,<24.5"

[package]
name = "jupyterlab_dyno"
version = "0.0.1"

[package.build]
backend = { name = "pixi-build-python", version = "==0.3.2" }

[package.host-dependencies] 
hatchling = ">=1.5.0"
hatch-nodejs-version = ">=0.3.2"
hatch-jupyter-builder = ">=0.5.0"
nodejs = ">=24.4.0,<24.5"
jupyterlab = ">=4.0.0,<5"

[package.run-dependencies]
dyno = ">=0.1.5.dev7"
xeus-python = ">=0.17.4,<0.18"
nlohmann_json = "==3.11.3"
