[workspace]
channels = ["conda-forge", "https://repo.prefix.dev/econforge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[tasks]
lab = "jupyter lab"
watch = "jlpm watch & jupyter lab"

[dependencies]
jupyterlab = ">=4.0.0,<5"
jupyterlab_dyno = { path = "." }
nodejs = ">=24.4.0,<24.5"
jupyterlab-myst = ">=2.4.2,<3"
tempita = ">=0.6.0,<0.7"
vega_datasets = ">=0.9.0,<0.10"
interegular = ">=0.3.3,<0.4"
altair = ">=5.5.0,<6"
rich = ">=14.1.0,<15"
comm = ">=0.2.3,<0.3"

[package]
name = "jupyterlab_dyno"
version = "0.0.2"

[package.build]
backend = { name = "pixi-build-python", version = "==0.3.2" }

[package.host-dependencies] 
hatchling = ">=1.5.0"
hatch-nodejs-version = ">=0.3.2"
hatch-jupyter-builder = ">=0.5.0"
nodejs = ">=24.4.0,<24.5"
jupyterlab = ">=4.0.0,<5"


[package.run-dependencies]
dyno = { path = "/home/pablo/Econforge/dyno.py"}
#dyno = ">=0.1.5.dev7"
#dyno = ">=0.1.6"
xeus-python = ">=0.17.4,<0.18"
nlohmann_json = "==3.12"
